name: Release Locale

on:
  push:
    tags:
      - v*

jobs:
  package:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract tag
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Extract version
        run: |
          VERSION=$(echo $TAG | sed 's/^v\([0-9]*\.[0-9]*\.[0-9]*\)-.*$/\1/')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      
      - name: Extract language code
        run: |
          LANG=$(echo $TAG | sed 's/^v[0-9]*\.[0-9]*\.[0-9]*-\(.*\)$/\1/')
          echo "LANG=${LANG}" >> $GITHUB_ENV
      
      - name: Check locale to release
        run: |
          ls -lah locales/$LANG

      - name: Install DSW Locale Packager
        run: |
          npm install @ds-wizard/locale-packager@0.2.0

      - name: Create locale ZIP package
        run: |
          mkdir out
          npx dsw-locale-packager locales/$LANG -o dsw_${{ env.LANG }}_${{ env.VERSION }}.zip -z
          
      - name: Create release and upload ZIP
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "out/dsw_${{ env.LANG }}_${{ env.VERSION }}.zip"
          artifactContentType: application/zip
          prerelease: ${{ steps.check_prerelease.outputs.is_prerelease }}
          replacesArtifacts: true
